spring:
  application:
    name: room-service
  profiles:
    active: prod
  config:
    import: configserver:http://config:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
    register-with-eureka: true
    fetch-registry: true