apiVersion: v1
kind: Pod
metadata:
  name: access-test
spec:
  containers:
    - name: access-test-container
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          apk add --no-cache curl && \
          curl -X GET <target-url> # 요청할 URL
      restartPolicy: Never