# role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer-binding
  namespace: default  # 네임스페이스가 일치해야 함
subjects:
  - kind: ServiceAccount
    name: jenkins  # 위에서 생성한 서비스 계정 이름
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-deployer  # 위에서 생성한 Role의 이름