spring:
  application:
    name: chat-service

  web:
    resources:
      add-mappings: false

  data:
    redis:
      host: 223.130.128.187  # Redis 서버 호스트
      port: 6379        # Redis 서버 포트
      password: password    # Redis 서버 비밀번호
      lettuce:
        pool:
          max-active: 8       # 최대 활성 연결 수
          max-idle: 8         # 최대 유휴 연결 수
          min-idle: 0         # 최소 유휴 연결 수
          max-wait: 10000ms   # 최대 대기 시간 (밀리초)

    mongodb:
      uri: mongodb://root:1234@223.130.128.187:27017/parandb?authSource=admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://223.130.156.167:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: 223.130.128.187

server:
  port: 8081
