server:
  port: 8083

naver:
  client-id: Hlz9JqBuVxtAsSSKyWHw
  client-secret-key: UamL61rm7F

eureka:
  client:
    service-url:
      default-zone: http://223.130.156.167:8761/eureka/


spring:
  application:
    name: room-service

  management:
    endpoints:
      web:
        exposure:
          include: health,info
  datasource:
    url: jdbc:mysql://223.130.128.187:3306/parandb?zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect