apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  labels:
    app: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: cheonghalim/paranmanzang:config
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: config
spec:
  selector:
    app: config
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
